<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260825055613 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE github_issue (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, repo VARCHAR(255) NOT NULL, number INT NOT NULL, title VARCHAR(500) NOT NULL, url VARCHAR(500) NOT NULL, github_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, github_updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, triage_status VARCHAR(255) NOT NULL, synced_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_REPO_NUMBER ON github_issue (repo, number)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE github_issue');
    }
}
